USE ROLE ACCOUNTADMIN;
USE DATABASE DEMO_COMMON;
  --Developer roles
CREATE OR ALTER ROLE SNOWFLAKE_DEVELOPER;	
GRANT ROLE SYSADMIN TO ROLE SNOWFLAKE_DEVELOPER;


 --Functional role
CREATE OR ALTER ROLE SNOWFLAKE_ANALYST;	
CREATE OR ALTER ROLE SNOWFLAKE_END_USER;
CREATE OR ALTER ROLE SNOWFLAKE_DATA_SCIENTIST;

-- Functional Domain Roles

CREATE OR ALTER ROLE SNOWFLAKE_DEMO_DB;


CREATE OR ALTER ROLE SNOWFLAKE_DEMO_DB_PU;



-- make SYSADMIN parent to the new role(s)
GRANT ROLE SNOWFLAKE_ANALYST TO ROLE SYSADMIN;
GRANT ROLE SNOWFLAKE_END_USER TO ROLE SYSADMIN;
GRANT ROLE SNOWFLAKE_DATA_SCIENTIST TO ROLE SYSADMIN;


GRANT ROLE SNOWFLAKE_DEMO_DB TO ROLE SYSADMIN;



GRANT ROLE SNOWFLAKE_DEMO_DB_PU TO ROLE SYSADMIN;


 ---ACCESS level roles foe every database, because they might have different users in the different schemas and databases in future



USE DATABASE DEMO_DB;
CREATE OR ALTER ROLE DEMO_DB_BRONZE_SR;
CREATE OR ALTER ROLE DEMO_DB_SILVER_SR;
CREATE OR ALTER ROLE DEMO_DB_GOLD_SR;
CREATE OR ALTER ROLE DEMO_DB_GOLD_ALL;

GRANT ROLE DEMO_DB_BRONZE_SR to ROLE SNOWFLAKE_ANALYST;
GRANT ROLE DEMO_DB_SILVER_SR to ROLE SNOWFLAKE_ANALYST;
GRANT ROLE DEMO_DB_GOLD_ALL TO ROLE SNOWFLAKE_ANALYST;

GRANT ROLE DEMO_DB_GOLD_SR TO ROLE SNOWFLAKE_END_USER;


GRANT ROLE DEMO_DB_BRONZE_SR to ROLE SNOWFLAKE_DATA_SCIENTIST;
GRANT ROLE DEMO_DB_SILVER_SR to ROLE SNOWFLAKE_DATA_SCIENTIST;


GRANT ROLE DEMO_DB_GOLD_SR TO ROLE SNOWFLAKE_DATA_SCIENTIST;

GRANT ROLE DEMO_DB_BRONZE_SR to ROLE SNOWFLAKE_DEMO_DB;
GRANT ROLE DEMO_DB_SILVER_SR to ROLE SNOWFLAKE_DEMO_DB;

GRANT ROLE DEMO_DB_GOLD_SR to ROLE SNOWFLAKE_DEMO_DB;

GRANT ROLE DEMO_DB_BRONZE_SR to ROLE SNOWFLAKE_DEMO_DB_PU;
GRANT ROLE DEMO_DB_SILVER_SR to ROLE SNOWFLAKE_DEMO_DB_PU;
GRANT ROLE DEMO_DB_GOLD_ALL to ROLE SNOWFLAKE_DEMO_DB_PU;

GRANT USAGE ON DATABASE DEMO_DB TO ROLE DEMO_DB_BRONZE_SR;
GRANT USAGE ON DATABASE DEMO_DB TO ROLE DEMO_DB_SILVER_SR;
GRANT USAGE ON DATABASE DEMO_DB TO ROLE DEMO_DB_GOLD_SR;
GRANT USAGE ON DATABASE DEMO_DB TO ROLE DEMO_DB_GOLD_ALL;

REVOKE OWNERSHIP ON FUTURE VIEWS IN SCHEMA DEMO_DB.GOLD FROM ROLE  SNOWFLAKE_ANALYST ;
GRANT OWNERSHIP ON  FUTURE VIEWS IN SCHEMA DEMO_DB.GOLD TO ROLE SNOWFLAKE_ANALYST ;


GRANT USAGE ON SCHEMA DEMO_DB.BRONZE TO ROLE DEMO_DB_BRONZE_SR;
GRANT USAGE ON SCHEMA DEMO_DB.SILVER TO ROLE DEMO_DB_SILVER_SR;


GRANT USAGE ON SCHEMA DEMO_DB.GOLD TO ROLE DEMO_DB_GOLD_SR;
GRANT ALL PRIVILEGES ON SCHEMA DEMO_DB.GOLD TO ROLE DEMO_DB_GOLD_ALL;

GRANT SELECT ON ALL VIEWS IN SCHEMA DEMO_DB.BRONZE TO ROLE DEMO_DB_BRONZE_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEMO_DB.BRONZE TO ROLE DEMO_DB_BRONZE_SR;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_DB.BRONZE TO ROLE DEMO_DB_BRONZE_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_DB.BRONZE TO ROLE DEMO_DB_BRONZE_SR;

GRANT SELECT ON ALL VIEWS IN SCHEMA DEMO_DB.SILVER TO ROLE DEMO_DB_SILVER_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEMO_DB.SILVER TO ROLE DEMO_DB_SILVER_SR;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_DB.SILVER TO ROLE DEMO_DB_SILVER_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_DB.SILVER TO ROLE DEMO_DB_SILVER_SR;

GRANT SELECT ON ALL VIEWS IN SCHEMA DEMO_DB.GOLD TO ROLE DEMO_DB_GOLD_SR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA DEMO_DB.GOLD TO ROLE DEMO_DB_GOLD_SR;
GRANT SELECT ON ALL TABLES IN SCHEMA DEMO_DB.GOLD TO ROLE DEMO_DB_GOLD_SR;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEMO_DB.GOLD TO ROLE DEMO_DB_GOLD_SR;

GRANT ALL ON ALL VIEWS IN SCHEMA DEMO_DB.GOLD TO ROLE DEMO_DB_GOLD_ALL;
GRANT ALL ON FUTURE VIEWS IN SCHEMA DEMO_DB.GOLD TO ROLE DEMO_DB_GOLD_ALL;
GRANT ALL ON ALL TABLES IN SCHEMA DEMO_DB.GOLD TO ROLE DEMO_DB_GOLD_ALL;
GRANT ALL ON FUTURE TABLES IN SCHEMA DEMO_DB.GOLD TO ROLE DEMO_DB_GOLD_ALL;



--Warehouses Grants

GRANT USAGE ON WAREHOUSE WH_END_USERS to role SNOWFLAKE_ANALYST;
GRANT USAGE ON WAREHOUSE   WH_DEV TO role SNOWFLAKE_ANALYST;
GRANT USAGE ON WAREHOUSE   WH_DEV TO role SNOWFLAKE_DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE WH_END_USERS to role SNOWFLAKE_END_USER;

-- Warehouse Grants for the domain functional groups

GRANT USAGE ON WAREHOUSE WH_BU to role SNOWFLAKE_DEMO_DB;
	


